final/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts import views

app_name= 'accounts'

urlpatterns=[
            url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
            url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
            url(r'^signup/$',views.SignUp.as_view(template_name='accounts/signup.html'),name='signup'),

]

final/final/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns=[ url(r'^admin/', admin.site.urls),
    url(r'',include('posts.urls')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test' ),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks' ),
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns=[ url(r'^admin/', admin.site.urls),
    url(r'',include('posts.urls',namespace='post') ),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test' ),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks' ),
]

mysite/posts/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from posts import views


urlpatterns=[
        url(r'^',views.PostListView.as_view(),name='post_list'),
    url(r'^(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^search/', views.SearchResultsView.as_view(), name='search_results'),
            ]

web/urls.py
from django.contrib import admin
from django.urls import path
from signup.views import UserCreateView
from signup import views
from django.http import HttpResponsePermanentRedirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', UserCreateView.as_view()),
]

mysite/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from posts.models import Post
from django.utils import timezone
from django.db.models import Q
from posts.forms import PostForm
from . import forms

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.contrib.auth import get_user_model
User = get_user_model()


class PostListView(ListView):
    model=Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'posts/post_detail.html'
    form_class = PostForm

    model = Post

    """def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)"""

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    template_name = 'posts/post_detail.html'

    form_class = PostForm

    model = Post


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'posts/post_list.html'

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

class SearchResultsView(ListView):
    model = Post
    template_name = 'posts/search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query)
        )
        return object_list
#######################################
## Functions that require a pk match ##
#######################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

mysite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookWorms NSU</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'static/mysite/css/master.css' %}">


  </head>


  <body>
    <!--Navigation bar-->
      <nav class="navbar navbar-inverse navbar-fixed-top" id="transmenu">
          <div class="container">
              <div class="navbar-header"><a class="navbar-brand navbar-link" href="{% url 'post:post_list' %}">Bookworms NSU</a>
                  <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
              </div>
              <div class="collapse navbar-collapse" id="navcol-1">
                  <ul class="nav navbar-nav">
                    {% if user.is_authenticated %}
                      <li role="presentation"><a href="#">Academic </a></li>
                      <li role="presentation"><a href="#">Non Academic</a></li>

                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <li role="presentation">
                          <a href="#"> </a>
                      </li>
                      <li role="presentation"><a href="#">Your Posts</a></li>
                      <button class="btn btn-success navbar-btn navbar-right" id= "btn-createad" type="button"><a href="{% url 'post:post_new' %}" >Create an ad</a></button>
                      <li role="presentation"><a href="{% url 'accounts:logout' %}">Logout</a></li>

                      {% else %}
                      <li role="presentation"><a href="#">Academic </a></li>
                      <li role="presentation"><a href="#">Non Academic</a></li>
                      <form action="{% url 'post:search_results' %}" method="get">
                      <input name="q" type="text" placeholder="Search...">
                      </form>
                      </form>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <li role="presentation">
                          <a href="#"> </a>
                      </li>
                      <li role="presentation"><a href="{% url 'accounts:login' %}">Log In</a></li>
                      <li role="presentation"><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                      <button class="btn btn-success navbar-btn navbar-right" id= "btn-createad" type="button"> Create an ad</button>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </nav>


    <div class="container mycontent">
      {% block content %}

      {% endblock %}

    </div>



<!--<canvas id="canvas"></canvas>-->



</body>
<!--<script src="{% static "mysite/js/master.js"%}" type="text/javascript" ></script>-->
</html>